### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by nunomaduro** [narration/narration#1]
I'm looking for someone to come up with a nice logo for this framework. Can you help? 💖

**Comment by mirzazulfan** [comment]
Hi @nunomaduro , what do you think about this? if you have an idea please share with me, it would be better for me. Best Regard.
![narration logo](https://user-images.githubusercontent.com/36124339/51228943-11ba0e80-198d-11e9-8066-c9d70d22999a.png)

**Comment by szepeviktor** [comment]
+1 for bottom left

**Comment by nunomaduro** [comment]
+1 for the bottom left.

**Comment by mirzazulfan** [comment]
Thanks for your response @nunomaduro and @szepeviktor . Im glad you like it. Should i create a pr and sent all files?

**Comment by nunomaduro** [comment]
Just pull request them into 
https://github.com/narration/art.

Thanks for this work, credits are going to be addressed soon as the framework get public.

**Comment by mirzazulfan** [comment]
Hi @nunomaduro . I can't make a pull request and fork in that repo https://github.com/narration/art. Maybe you can do it. You can download all files [here](https://drive.google.com/drive/folders/1IXptkYr0m4XhHteWCIev07trSnruIL6t?ogsrc=32) . Best regard.

**Comment by nunomaduro** [comment]
@mirzazulfan You made a great job. Thanks for this work, credits are going to be addressed soon as the framework get public. It may take a while. Thanks!

**Comment by nunomaduro** [comment]
@mirzazulfan Just added you as maintainer of narration/art: https://github.com/narration/art/invitations
