### ISSUE TITLE
RFC: Database

### ISSUE THREAD

**Issue by nunomaduro** [narration/narration#13]
Should we provide a default database layer? If yes, what and how?

**Comment by vistik** [comment]
Hi @nunomaduro,

Maybe you could give a short background story on why you decided to create this framework? Was it build for a specific task (microservices etc), to promote "good coding standards" or with the idea of becoming a fully fledged framework used in the real world by other people?

If your idea is to create a framework that other people actually use (I think this should be the goal :) ) then it would make most sense IMHO to provide a default way of connection and interaction with a database. Most people that would try this framework out would expect that.

On the other hand if you want this framework to stay very lightweight (again this depends on your initial idea) the database component could be opt-in, but still should be available pretty easily.

**Comment by maxalmonte14** [comment]
I personally don't think that adding a default database layer is a good idea, it would be another module to maintain, and it's not strictly necessary. Yes, most web applications will use a database, granted, but developers should decide how to communicate with it.

ASP .NET Core is a good example of this, a database layer is not included by default, you can configure it if you need to in no time by adding [Entity Framework Core](https://github.com/aspnet/EntityFrameworkCore) or even another option like [Dapper](https://github.com/StackExchange/Dapper) if you want. I'm not trying to say that Narration should be a PHP port of ASP .NET Core, but I think it's a good reference.

An alternative could be creating a separate repo with an official (but not included by default) database layer implementation.

Porting existing ORMs and Data Mappers could be an option too, that way developers can interact with the database using the tools they already know, say [Doctrine](https://www.doctrine-project.org/projects/orm.html) for example.

**Comment by nunomaduro** [comment]
@maxalmonte14 I agree with you. Was example, I am using Narration on PHP Insights where I don't need a database layer.
