### ISSUE TITLE
RFC: Intefaces naming convention

### ISSUE THREAD

**Issue by tuanpht** [narration/narration#15]
Since we are using dependency injection, we mostly refer to the interface, e.g. `Domain\Contracts\Repositories\TaskRepositoryInterface`.

I think we can remove the `Interface` suffix.

Nikola Poša explained more detail in his blog: https://blog.nikolaposa.in.rs/2019/01/06/better-naming-convention/

What do you think?

**Comment by nunomaduro** [comment]
Thanks for open this issue.

In my opinion i don't find elegant making alias while importing classes, here is an example:
```php
use Domain\Interfaces\Repositories\TaskRepository as TaskRepositoryInterface;

final class TaskRepository implements TaskRepositoryInterface {}
```

**Comment by tuanpht** [comment]
I think we can reduce the naming, folder structure, and no need to use alias import, for example:

Contract/Interface:
```php
namespace Domain\Contracts\Repositories;

interface TaskRepository {}
```

Infrastructure/Implemetations:
```php
namespace Infrastructure\Repositories;

use Domain\Contracts\Repositories\TaskRepository;

final class DbTaskRepository implements TaskRepository {}
```
```php
namespace Infrastructure\Repositories;

use Domain\Contracts\Repositories\TaskRepository;

final class RedisTaskRepository implements TaskRepository {}
```
...

Using in HTTP Request handlers:
```php
namespace Application\Http\RequestHandlers;

use Domain\Contracts\Repositories\TaskRepository;

final class Index
{
    public function __invoke(TaskRepository $taskRepository): array
    {
        //
    }
}
```

Using in Console Commands:
```php
namespace Application\Console\Commands;

use Domain\Contracts\Repositories\TaskRepository;

final class FooCommand
{
    public function __construct(TaskRepository $taskRepository)
    {
        // ...
    }
}
```

Our command, request handler refer to `TaskRepository`, and only the IoC Container know about `DbTaskRepository`.

**Comment by tutNichts** [comment]
@tuanpht question: will there be a `*TaskRepository` instance for e.g. `Db`, `Redis`, ...? I guess the repository shouldn't have to know how those data gets saved - or did I misunderstood something as we have not much informations yet?

BTT: I more like @nunomaduro's approach.

**Comment by tuanpht** [comment]
@tutNichts 
`Db`, `Redis`... is just a example for there may be multiple implementations for an interface.

About 
> The repository shouldn't have to know how those data gets saved

Yes if you are talking about interface. And we also only refer to interface `TaskRepository` when we want using it it controller, console command, task queue... The `DbTaskRepository` is only used once in IoC container:
```php
final class Repositories
{
    /**
     * Injects repositories into the container definitions.
     *
     * @return mixed[]
     */
    public function __invoke(): array
    {
        return [
            TaskRepository::class => DbTaskRepository::class,
        ];
    }
}
```
I mean we will use `Domain\Contracts\Repositories\TaskRepositoryInterface` more than `Infrastructure\Persistence\Repositories\TaskRepository`, so we can remove the meaningless suffix `Interface` :smiley:

**Comment by nunomaduro** [comment]
Alright, going with your convention for now: https://github.com/narration/narration/commit/5316be6b25793d9b4079daf66b539b3e4676c202.
