### ISSUE TITLE
Website needed

### ISSUE THREAD

**Issue by nunomaduro** [narration/narration#2]
I'm looking for someone to come up with a nice website for this framework. Can you help? 💖

**Comment by szepeviktor** [comment]
Will it be better than Laravel?

Will there be comparison videos on YouTube?

**Comment by nunomaduro** [comment]
@szepeviktor This is a work in progress. I don't know nothing yet. But your help is very welcome!

**Comment by nunomaduro** [comment]
The website should go to: https://github.com/narration/website

**Comment by ianrodrigues** [comment]
@nunomaduro do you have any idea on how the website would look like?

**Comment by nunomaduro** [comment]
Just an website with normal framework documentation. The only thing that I believe it's imporant is to be able to document in Markdown.

I was thinking about Vue Press Or https://jigsaw.tighten.co.

Concerning "Look Like" I am open for everthing.

**Comment by ianrodrigues** [comment]
@nunomaduro [here](https://drive.google.com/file/d/1kKrC3kpg3ZG1eOOsy4Yno4smap-zf8OV/view?usp=sharing) is just a first try with the JIgsaw docs template

**Comment by nunomaduro** [comment]
I really like it! Nice 👍

**Comment by ianrodrigues** [comment]
here: https://github.com/narration/website/issues/1

**Comment by nunomaduro** [comment]
Currently contacting the domain narration.com, if not available I am going to narrationphp.com

**Comment by ianrodrigues** [comment]
Cool! I'll publish the code on the website repo. I think you can close this thread.
