### ISSUE TITLE
Website domain

### ISSUE THREAD

**Issue by nunomaduro** [narration/narration#9]
Looks like we are going for `narrationphp.com`. What do you guys think?

**Comment by josepostiga** [comment]
What about narration-framework.com?

**Comment by nunomaduro** [comment]
Still prefer the narrationphp, we already have the twitter like that.

**Comment by pmayet** [comment]
narration.io or narration.sh

**Comment by tutNichts** [comment]
I also like narrationphp.com

**Comment by nunomaduro** [comment]
Done: narrationphp.com.

**Comment by vistik** [comment]
@nunomaduro what about narrationphp.dev? :)
